### PR TITLE
add file install method

### PR DESCRIPTION
**Pull request by juju4**
Allows to install from a file local to orchestrator

### CODE REVIEW

**Comment by carlosmmatos** [comment]
Hi @juju4  - thanks for opening the PR. Would you mind expanding on your specific scenario in order to better understand the ask here?

**Comment by juju4** [comment]
This allows to deploy directly from orchestrator system without need for console credentials or additional system (web server to store files)

**Comment by carlosmmatos** [comment]
@juju4 We can probably refine this a bit to be more inline with the project. For example, we're not going to implement a copy feature as that can be done in a pre-tasks outside the collection itself. However, we do believe in supporting local file path installations for all operating systems so this is something we would like to add. 

If you agree with the above, then we can contribute our recommended changes to your PR.

**Comment by carlosmmatos** [comment]
@juju4 Let me know if you are on board with the current proposed changes I have pushed to your PR.

Basically, this is how you would use it to get that same functionality you are after:

```yaml
---
- hosts: all
  tasks:
  - name: Copy falcon-sensor to remote
    ansible.builtin.copy:
      src: <path to falcon-sensor on orchestrator>
      dest: /tmp/falcon.deb

  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_install_method: file
      falcon_localfile_path: /tmp/falcon.deb
      falcon_localfile_cleanup: yes

**Comment by juju4** [comment]
LGTM. Thanks!

**Pull request merged**
