### PR TITLE
Add missing var causing windows installs to fail

### LINKED ISSUE #123: Error on TASK Set CID received from API
Just updated to 3.2.0 of the collection and now I'm getting the following error when running my playbook:

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Set CID received from API] ******************************************************************************************************
fatal: [hostname]: FAILED! => {"msg": "The conditional check 'not falcon_cid' failed. The error was: error while evaluating conditional (not falcon_cid): 'falcon_cid' is undefined\n\nThe error appears to be in '/etc/ansible/projects/crowdstrike/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_api.yml': line 91, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Set CID received from API\n  ^ here\n"}

Here's what my playbook looks like:
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
  vars:
    falcon_client_id: "{{ falcon_client_id }}"
    falcon_client_secret: "{{ falcon_client_secret }}"
    falcon_cloud: "api.us-2.crowdstrike.com"

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #123

### CODE REVIEW

**Comment by gillg** [comment]
Could you fix in the meantime replace `ansible.builtin.find` by `ansible.windows.win_find` which cause a fails if you don't have python ?

**Comment by redhatrises** [comment]
> Could you fix in the meantime replace `ansible.builtin.find` by `ansible.windows.win_find` which cause a fails if you don't have python ?

@gillg Please don't ask for additional fixing or functionality in a PR. Please do so in the existing issues, or create a new issue.

**Comment by gillg** [comment]
Sorry 😊 I was just passing here randomly, saw an open pr 3h ago, around windows issues I just jumped on it !
Many thanks for your quick fix.

**Comment by jurschel** [comment]
I think  you need to look again at this change.  It's failing now with this error. 

"argument for paths is of type System.Collections.Hashtable and we were unable to convert to list: System.Collections.Hashtable cannot be converted to a list"

**Comment by carlosmmatos** [comment]
> I think you need to look again at this change. It's failing now with this error.
> 
> "argument for paths is of type System.Collections.Hashtable and we were unable to convert to list: System.Collections.Hashtable cannot be converted to a list".
> 
> It seems to me that https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_stat_module.html#return-stat/path says it requires the absolute path to the file. The example provided here is c:\foo.ini. I'm not following why you need to invoke win_stat here as the variable is already assumed to be %SYSTEMROOT%\temp or in the docs your allowing us to use the variable falcon_windows_tmp_dir so that path is already defined and shouldn't need to be derived from win_stat. As you can see below the "filename" is the folder name and not a file under the tmp dir. `{ "changed": false, "invocation": { "module_args": { "path": "c:\\falcon-temp\\", "checksum_algorithm": "sha1", "get_checksum": true, "follow": false } }, "stat": { "ishidden": false, "owner": "BUILTIN\\Administrators", "isdir": true, "islnk": false, "lastwritetime": 1642454604.2204728, "isreg": false, "filename": "falcon-temp", "isarchive": false, "hlnk_targets": [], "isjunction": false, "isreadonly": false, "size": 312286800, "exists": true, "creationtime": 1642450725.0828702, "lastaccesstime": 1642454604.2204728, "nlink": 1, "isshared": false, "path": "c:\\falcon-temp\\", "attributes": "Directory" }, "_ansible_no_log": false }`
> 
> And here in the win_find you can see that filename is incorrect...
> 
> `{ "changed": false, "msg": "argument for paths is of type System.Collections.Hashtable and we were unable to convert to list: System.Collections.Hashtable cannot be converted to a list", "invocation": { "module_args": { "paths": { "stat": { "isshared": false, "lastaccesstime": 1642454604.2204728, "isarchive": false, "isdir": true, "islnk": false, "isreadonly": false, "isreg": false, "isjunction": false, "exists": true, "lastwritetime": 1642454604.2204728, "ishidden": false, "hlnk_targets": [], "creationtime": 1642450725.0828702, "size": 312286800, "owner": "BUILTIN\\Administrators", "attributes": "Directory", "path": "c:\\falcon-temp\\", "filename": "falcon-temp", "nlink": 1 }, "changed": false, "failed": false }, "use_regex": false, "file_type": "directory", "follow": false, "get_checksum": true, "hidden": false, "recurse": false, "checksum_algorithm": "sha1", "patterns": [ "ansible.*falcon" ], "age_stamp": "mtime" } }, "_ansible_no_log": false }`
> 
> Why not just delete the ansible.*falcon directory to cleanup?

@jurschel The reason for this change is because Ansible is not able to expand windows variables ie (%TEMP% or %SYSTEMROOT%) in other modules such as `win_find` - therefore in order to use the module correctly requires an intermediary step (`win_stat`) to get the expanded path in order to use in the `win_find` module..

This issue here should be resolved by #135 as we forgot to add the stat.path arg to the variable.

**Pull request merged**
