### PR TITLE
feat: add toggle for become on windows

### PR DESCRIPTION
**Pull request by chipselden**
This PR adds a new variable `falcon_windows_become` to the install, configure, and uninstall roles so that privilege escalation may be disabled if necessary.

Depending on how a Windows machine is configured and which user is used, becoming another user may be unnecessary.

### CODE REVIEW

**Comment by carlosmmatos** [comment]
@chipselden appreciate the PR. Going to run it through the CI but looking at it really quickly it makes sense.

**Review by carlosmmatos — APPROVED** [review]
lgtm

**Comment by chipselden** [comment]
Thanks so much for the quick work on this @carlosmmatos! Do you have a projected timeline for releasing a new version?

**Comment by carlosmmatos** [comment]
Soon.. hopefully by tomorrow EOD. Just going over some stuff and trying to handle low hanging fruit.

**Comment by carlosmmatos** [comment]
@chipselden 4.6.0 has been released!

In case you don't have notifications for new releases set up - you can do this by:

Selecting the `watch/unwatch` dropdown:
CleanShot 2024-09-06 at 10 28 56@2x

Then select -> custom
CleanShot 2024-09-06 at 10 31 39@2x

And finally you can add releases
CleanShot 2024-09-06 at 10 32 21@2x

**Pull request merged**
